### PR TITLE
[DERCBOT-918] Gunicorn timeout and asynchronous processing

### PR DESCRIPTION
**Pull request by assouktim**

### CODE REVIEW

**Review by Benvii — CHANGES_REQUESTED** [review]
Ok but all decorators need to be async this means that each decorators on the request call stack need to explicitly be async and call the func this way `await func`.

Change needs to be done on : 

- [x] opensearch_exception_handler

I didn't find any else missing, good work 👍️

**Comment by assouktim** [comment]
the opensearch_exception_handler has also been made asynchronous

**Comment by Benvii** [comment]
Ok thanks for this detail about OpenSearch langchain integration, do you have any ticket / issue about it ?
Can we add any comment for it in the code ?

This could be done in langchain using https://github.com/opensearch-project/opensearch-py/blob/main/guides/async.md

**Review by Benvii — DISMISSED** [review]
Thanks 👍️,

**Pull request merged**
