### PR TITLE
[DERCBOT-940] Export langsmith dataset run results

### PR DESCRIPTION
**Pull request by assouktim**

### CODE REVIEW

**Comment by assouktim** [comment]
The need has evolved, we will have to add the theme of the question. WIP

**Comment by assouktim** [comment]
Ready for exam

**Review by AurelienSylvan — APPROVED** [review]
LGTM

**Comment by assouktim** [comment]
PR approuvé, mais pas mergé directement sur la branche RAG/develop.
Ce dev est embarqué sur la PR https://github.com/theopenconversationkit/tock/pull/1621

**Pull request closed without merging**
